project:
  type: website
  output-dir: ../docs

website:
  title: "swstrebe.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contact.qmd
        text: Contact
        


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
